volumes:
  minio_data:
  minio_config:

networks:
  triplens:
  airflow:

services:
  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z-cpuv1
    container_name: minio_astro

    env_file:
      - .env

    ports:
      - "9100:9000"
      - "9101:9001"

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data
      - minio_config:/root/.minio

    networks:
      - triplens
      - airflow