name: Build and Push Astro Image to Docker Hub

on:
  workflow_run:
    workflows: ["dbt CI"] # Must match your CI workflow name exactly
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Crucial safety check: Only run if the dbt-CI workflow actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/triplens_global:latest
            ${{ secrets.DOCKER_USERNAME }}/triplens_global:${{ github.event.workflow_run.head_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max